version: "3.4"
services:
  beacon-chain:
    image: "beacon-chain.stake.dnp.dappnode.eth:0.1.0"
    build:
      context: beacon-chain
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - 12000/udp
      - "13000"
    restart: unless-stopped
    environment:
      XDAI_RPC_URL: "https://sokol.poa.network/"
      DEPLOYMENT_BLOCK: 22694907
      EXTRA_OPTS: ""
  validator:
    image: "validator.stake.dnp.dappnode.eth:0.1.0"
    build:
      context: validator
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      BEACON_RPC_PROVIDER: "beacon-chain.stake.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.stake.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
